image: python:3.11-slim

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

# Cache pip dependencies between jobs
cache:
  paths:
    - .pip-cache/
    - venv/

services:
  - postgres:15-alpine

stages:
  - test

before_script:
  - python -V
  - python -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    # Run migrations
    - alembic upgrade head
    # Run tests with coverage
    - pytest tests/ -v --cov=app --cov-report=term-missing --cov-report=xml
  coverage: '/(?i)total.*? (100(?:\.0+)?|[1-9]?\d(?:\.\d+)?)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    when: always
    expire_in: 1 week
  
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG 