version: '3.8'

services:
  api:
    build: .
    container_name: tmdb-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tmdb
      - POSTGRES_PORT=5432
      - TMDB_API_KEY=${TMDB_API_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14-alpine
    container_name: tmdb-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tmdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
